package com.machine.manager;

import org.apache.commons.codec.binary.Base64;

import java.nio.charset.StandardCharsets;

public class Main {
    public static void main(String[] args) {

        String s = "1234567891013";
        //字符串转字节数组
        byte[] array = s.getBytes(StandardCharsets.UTF_8);

        //输出经过base64编码过后的字符串（有特殊字符不适合作为url）
        String writing1 = Base64.encodeBase64String(array);
        System.out.println("编码1：" + writing1);

        //输出经过base64编码过后的字符串（无特殊字符适合作为url）
        String writing2 = Base64.encodeBase64URLSafeString(array);
        System.out.println("编码2：" + writing2);

        //解码1
        System.out.println("解码1：" + new String(new Base64().decode(writing1)));
        //解码2
        System.out.println("解码2：" + new String(new Base64().decode(writing2)));


        String xxx = "CgAKAAoACgAKAAoACgAKAAoACgAKAAoACgAKAAoACgDyBO0E5wTgBNkE0gTMBMUEvwS8BLcEsQStBKoEpASgBJ0ElwSUBJAEjQSJBIUEgQR+BHoEdQR0BG8EbgRpBGcEZARkBF4EXAQAAAAAAAAAAGwDVANKA0QDQAM4AzMDLgMrAykDIAMeAxsDGQMYAxcDGwMZAxgDGAMZAxcDGAMbAxwDHgMdAxwDHQMcAx8DIwMlAyUDKwMxAzADMwM2AzoDPwNCA0EDTgNpAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeQl2CXQJcglyCXEJbgltCWsJaQlmCWQJZglpCWkJawluCW0JbQlwCXAJdgm7CcAJsQmmCZ0JlQmUCZAJjwmQCZUJnwmwCeUJPAq2CgAAAAAAAIMLyAqUCgAAkAqSCpIKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1CFLIbIgDSCAH/AeAABDGkcaghprGmgaAAAAAAAAdxhYGFgYQhhTGGoYfhiNGJ4Yqxi0GAAAAACRIjIizSFrIQ8htSBWIAQgtB9fHxQfxh58HlUeWh52HpEerB7KHuoeEx9HH2sfjh+0H9gf+x8dIFUg1yD4IDYhAAAAAAAAAADGIXUhAAAIGZcYZxg9GBIY5he/F5gXcRdHFyEX+xbTFgAAzRPaE4IUOxQyFLMThxMqFMEUKBXgE3oTghOlFOIU9BQTFTgVYRWFFakV0RUIFnAWJBd7F9cXAAAAAK0c2hzyHLYcAAAAAAAAnw2aDQAAAAAAAAAAqhqaGiMbVhsiGxUbHxtRGwAAAAAAAAAAAAAAAAAAAAAAAAAAbAwAAGkMaAyXDAwNBA34DPQM8QzxDPYMAg0iDZ4NQw5HDkcOAAAFDowNIw4AAAAAAAD6DQAAAAAAAAAAAAAAAAAAJxAREK0PnQ+xD4cPew+KD6APvw/pDysQAAAAAAAAAADfGU4aLRuMGwAAOCFPIUchRiFFIUkhVyFjIXchlSG+IfIhMyKFIgAALS42Lj8uTi5aLmMuTS4AAAAAAAADF6AWoxamFqkWsRa7Fr8WXBZbFgAAAAAAAAAAPRIAAAAAAAAAAAAAAAAAAAAAAABdDQAAAAAAAAAAAAAAAAAAAAAAAAAAAABWDCcMzAtpCwwLlwodCtUJAABrCT0JDwnpCMcIpAiCCGMIQAgZCPAHyQeoB4cHbAdOBzQHAAAAAAAAAAAAAAAAAADMCgAAAAAAAAAAAAAAABQHAgf1BvgG/gYEBwUH+AbnBtgGyAa6Bq0GnQadBqQGrAa1BroGwgbKBtIG2QbiBuAG0wbIBskGzgbZBuQGAAAAAAAAAAAAANcGAAAAAAAA+QYCBwwHFAceBygHNQc/B0gHUgdhB2wHdgeDB48HmwepB7gHxQfUB+EH8QcACA8IHQgvCD4ITQheCG4IfwiPCJ4IsQjFCNYI6gj9CBQJJgk8CVMJaQl8CZUJqgnBCdsJ8gkMCiYKQgpcCnoKmQq8CvMKEgsxC1MLeQudC8QL6QsODDMMXwyNDLkM6gwYDUcNeQ2xDeMNGg5YDpcO0w4VD14PvA/6D0YQmBDkEDcRjhHiEUQSphIGE3QT5RN6FPsUhBUbFrgWXRcIGL8YmRleGkIbNRxCHWkezh9TIYMikyKLIoQifiJ5IngidCJvImciZSJdIgAAcx3pHKscexxZHDwcJBwRHAMc2hsAAAAAAAAAAAAAAAAAAMwJ1AnSCdEJ1QnVCdIJ1gnWCdYJ2AnYCdoJ3AncCd4J4AngCeIJ5QnnCekJ7AnvCfIJ9An1CfgJ+wn8CQAKBQoFCggKDAoRChYKGAocCh4KJAomCigKLAowCjUKOwo9CkMKRwpKClEKVgpaCmEKZwpsCnEKdgp/CocKjAqTCpYKgQp7Cq4KvArCCskKzwrYCt8K5wruCvYKAAsFCw4LFgsfCysLNQs7C0YLUQtbC2YLcgt8C4gLkQucC6kLtQvAC8wL1wvkC+8L+wsHDBIMHwwqDDgMRQxVDGEMcgyBDJAMoQyqDK0MlQy8DNkM5wz6DAgNGg0rDT0NTw1hDXQNhw0KAAoACgAKAAoACgAKAAoACgAKAAoACgAKAAoACgAKAAoACgA=";
        System.out.println("解码3：" + new String(new Base64().decode(xxx)));
    }
}

